<?php

return [
    'renderer-config' => [
        'socket.url' => config('nitro.socket_url'),
        'asset.url' => config('nitro.asset_path'),
        'image.library.url' => config('nitro.c_images_path'),
        'hof.furni.url' => config('nitro.hof_furni_path'),
        'images.url' => config('nitro.image_path'),
        'gamedata.url' => config('nitro.asset_gamedata_path'),
        'sounds.url' => sprintf('%s/%s.mp3', config('nitro.sounds_path'), '%sample%'),
        'external.texts.url' => [
            sprintf('%s/ExternalTexts.json', config('nitro.asset_gamedata_path')),
            sprintf('%s/UITexts.json', config('nitro.asset_gamedata_path')),
        ],
        'external.samples.url' => sprintf('%s/sound_machine_sample_%s.mp3', config('nitro.mp3_path'), '%sample%'),
        'furnidata.url' => sprintf('%s/FurnitureData.json', config('nitro.asset_gamedata_path')),
        'productdata.url' => sprintf('%s/ProductData.json', config('nitro.asset_gamedata_path')),
        'avatar.actions.url' => sprintf('%s/HabboAvatarActions.json', config('nitro.asset_gamedata_path')),
        'avatar.figuredata.url' => sprintf('%s/FigureData.json', config('nitro.asset_gamedata_path')),
        'avatar.figuremap.url' => sprintf('%s/FigureMap.json', config('nitro.asset_gamedata_path')),
        'avatar.effectmap.url' => sprintf('%s/EffectMap.json', config('nitro.asset_gamedata_path')),
        'avatar.asset.url' => sprintf('%s/%s.nitro', config('nitro.figure_path'), '%libname%'),
        'avatar.asset.effect.url' => sprintf('%s/%s.nitro', config('nitro.effect_path'), '%libname%'),
        'furni.asset.url' => sprintf('%s/%s.nitro', config('nitro.furniture_path'), '%libname%'),
        'furni.asset.icon.url' => sprintf('%s/%s_icon.png', config('nitro.icons_path'), '%libname%%param%'),
        'pet.asset.url' => sprintf('%s/%s.nitro', config('nitro.pet_path'), '%libname%'),
        'generic.asset.url' => sprintf('%s/%s.nitro', config('nitro.generic_path'), '%libname%'),
        'badge.asset.url' => sprintf('%s/%s.gif', config('nitro.badge_path'), '%badgename%'),
        'furni.rotation.bounce.steps' => 20,
        'furni.rotation.bounce.height' => 0.0625,
        'enable.avatar.arrow' => false,
        'system.log.debug' => false,
        'system.log.warn' => false,
        'system.log.error' => false,
        'system.log.events' => false,
        'system.log.packets' => false,
        'system.fps.animation' => 24,
        'system.fps.max' => 60,
        'system.pong.manually' => true,
        'system.pong.interval.ms' => 20000,
        'room.color.skip.transition' => true,
        'room.landscapes.enabled' => true,
        'avatar.mandatory.libraries' => ['bd:1', 'li:0'],
        'avatar.mandatory.effect.libraries' => ['dance.1', 'dance.2', 'dance.3', 'dance.4'],
        'avatar.default.figuredata' => [
            'palettes' => [
                [
                    'id' => 1,
                    'colors' => [
                        [
                            'id' => 99999,
                            'index' => 1001,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'DDDDDD',
                        ],
                        [
                            'id' => 99998,
                            'index' => 1001,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FAFAFA',
                        ],
                    ],
                ],
                [
                    'id' => 3,
                    'colors' => [
                        [
                            'id' => 10001,
                            'index' => 1001,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'EEEEEE',
                        ],
                        [
                            'id' => 10002,
                            'index' => 1002,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FA3831',
                        ],
                        [
                            'id' => 10003,
                            'index' => 1003,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FD92A0',
                        ],
                        [
                            'id' => 10004,
                            'index' => 1004,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '2AC7D2',
                        ],
                        [
                            'id' => 10005,
                            'index' => 1005,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '35332C',
                        ],
                        [
                            'id' => 10006,
                            'index' => 1006,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'EFFF92',
                        ],
                        [
                            'id' => 10007,
                            'index' => 1007,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'C6FF98',
                        ],
                        [
                            'id' => 10008,
                            'index' => 1008,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FF925A',
                        ],
                        [
                            'id' => 10009,
                            'index' => 1009,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '9D597E',
                        ],
                        [
                            'id' => 10010,
                            'index' => 1010,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'B6F3FF',
                        ],
                        [
                            'id' => 10011,
                            'index' => 1011,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '6DFF33',
                        ],
                        [
                            'id' => 10012,
                            'index' => 1012,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '3378C9',
                        ],
                        [
                            'id' => 10013,
                            'index' => 1013,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FFB631',
                        ],
                        [
                            'id' => 10014,
                            'index' => 1014,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'DFA1E9',
                        ],
                        [
                            'id' => 10015,
                            'index' => 1015,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'F9FB32',
                        ],
                        [
                            'id' => 10016,
                            'index' => 1016,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'CAAF8F',
                        ],
                        [
                            'id' => 10017,
                            'index' => 1017,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'C5C6C5',
                        ],
                        [
                            'id' => 10018,
                            'index' => 1018,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '47623D',
                        ],
                        [
                            'id' => 10019,
                            'index' => 1019,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '8A8361',
                        ],
                        [
                            'id' => 10020,
                            'index' => 1020,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FF8C33',
                        ],
                        [
                            'id' => 10021,
                            'index' => 1021,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '54C627',
                        ],
                        [
                            'id' => 10022,
                            'index' => 1022,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '1E6C99',
                        ],
                        [
                            'id' => 10023,
                            'index' => 1023,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '984F88',
                        ],
                        [
                            'id' => 10024,
                            'index' => 1024,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '77C8FF',
                        ],
                        [
                            'id' => 10025,
                            'index' => 1025,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FFC08E',
                        ],
                        [
                            'id' => 10026,
                            'index' => 1026,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '3C4B87',
                        ],
                        [
                            'id' => 10027,
                            'index' => 1027,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '7C2C47',
                        ],
                        [
                            'id' => 10028,
                            'index' => 1028,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'D7FFE3',
                        ],
                        [
                            'id' => 10029,
                            'index' => 1029,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '8F3F1C',
                        ],
                        [
                            'id' => 10030,
                            'index' => 1030,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FF6393',
                        ],
                        [
                            'id' => 10031,
                            'index' => 1031,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => '1F9B79',
                        ],
                        [
                            'id' => 10032,
                            'index' => 1032,
                            'club' => 0,
                            'selectable' => false,
                            'hexCode' => 'FDFF33',
                        ],
                    ],
                ],
            ],
            'setTypes' => [
                [
                    'type' => 'hd',
                    'paletteId' => 1,
                    'mandatory_f_0' => true,
                    'mandatory_f_1' => true,
                    'mandatory_m_0' => true,
                    'mandatory_m_1' => true,
                    'sets' => [
                        [
                            'id' => 99999,
                            'gender' => 'U',
                            'club' => 0,
                            'colorable' => true,
                            'selectable' => false,
                            'preselectable' => false,
                            'sellable' => false,
                            'parts' => [
                                [
                                    'id' => 1,
                                    'type' => 'bd',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                                [
                                    'id' => 1,
                                    'type' => 'hd',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                                [
                                    'id' => 1,
                                    'type' => 'lh',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                                [
                                    'id' => 1,
                                    'type' => 'rh',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'type' => 'bds',
                    'paletteId' => 1,
                    'mandatory_f_0' => false,
                    'mandatory_f_1' => false,
                    'mandatory_m_0' => false,
                    'mandatory_m_1' => false,
                    'sets' => [
                        [
                            'id' => 10001,
                            'gender' => 'U',
                            'club' => 0,
                            'colorable' => true,
                            'selectable' => false,
                            'preselectable' => false,
                            'sellable' => false,
                            'parts' => [
                                [
                                    'id' => 10001,
                                    'type' => 'bds',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                                [
                                    'id' => 10001,
                                    'type' => 'lhs',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                                [
                                    'id' => 10001,
                                    'type' => 'rhs',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                            ],
                            'hiddenLayers' => [
                                ['partType' => 'bd'],
                                ['partType' => 'rh'],
                                ['partType' => 'lh'],
                            ],
                        ],
                    ],
                ],
                [
                    'type' => 'ss',
                    'paletteId' => 3,
                    'mandatory_f_0' => false,
                    'mandatory_f_1' => false,
                    'mandatory_m_0' => false,
                    'mandatory_m_1' => false,
                    'sets' => [
                        [
                            'id' => 10010,
                            'gender' => 'F',
                            'club' => 0,
                            'colorable' => true,
                            'selectable' => false,
                            'preselectable' => false,
                            'sellable' => false,
                            'parts' => [
                                [
                                    'id' => 10001,
                                    'type' => 'ss',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                            ],
                            'hiddenLayers' => [
                                ['partType' => 'ch'],
                                ['partType' => 'lg'],
                                ['partType' => 'ca'],
                                ['partType' => 'wa'],
                                ['partType' => 'sh'],
                                ['partType' => 'ls'],
                                ['partType' => 'rs'],
                                ['partType' => 'lc'],
                                ['partType' => 'rc'],
                                ['partType' => 'cc'],
                                ['partType' => 'cp'],
                            ],
                        ],
                        [
                            'id' => 10011,
                            'gender' => 'M',
                            'club' => 0,
                            'colorable' => true,
                            'selectable' => false,
                            'preselectable' => false,
                            'sellable' => false,
                            'parts' => [
                                [
                                    'id' => 10002,
                                    'type' => 'ss',
                                    'colorable' => true,
                                    'index' => 0,
                                    'colorindex' => 1,
                                ],
                            ],
                            'hiddenLayers' => [
                                ['partType' => 'ch'],
                                ['partType' => 'lg'],
                                ['partType' => 'ca'],
                                ['partType' => 'wa'],
                                ['partType' => 'sh'],
                                ['partType' => 'ls'],
                                ['partType' => 'rs'],
                                ['partType' => 'lc'],
                                ['partType' => 'rc'],
                                ['partType' => 'cc'],
                                ['partType' => 'cp'],
                            ],
                        ],
                    ],
                ],
            ],
        ],
        'avatar.default.actions' => [
            'actions' => [
                [
                    'id' => 'Default',
                    'state' => 'std',
                    'precedence' => 1000,
                    'main' => true,
                    'isDefault' => true,
                    'geometryType' => 'vertical',
                    'activePartSet' => 'figure',
                    'assetPartDefinition' => 'std',
                ],
            ],
        ],
        'pet.types' => [
            'dog',
            'cat',
            'croco',
            'terrier',
            'bear',
            'pig',
            'lion',
            'rhino',
            'spider',
            'turtle',
            'chicken',
            'frog',
            'dragon',
            'monster',
            'monkey',
            'horse',
            'monsterplant',
            'bunnyeaster',
            'bunnyevil',
            'bunnydepressed',
            'bunnylove',
            'pigeongood',
            'pigeonevil',
            'demonmonkey',
            'bearbaby',
            'terrierbaby',
            'gnome',
            'gnome',
            'kittenbaby',
            'puppybaby',
            'pigletbaby',
            'haloompa',
            'fools',
            'pterosaur',
            'velociraptor',
            'cow',
            'LeetPen',
            'bbwibb',
            'elephants',
        ],
        'preload.assets.urls' => [
            sprintf('%s/avatar_additions.nitro', config('nitro.generic_path')),
            sprintf('%s/group_badge.nitro', config('nitro.generic_path')),
            sprintf('%s/floor_editor.nitro', config('nitro.generic_path')),
            sprintf('%s/loading_icon.png', config('nitro.image_path')),
            sprintf('%s/clear_icon.png', config('nitro.image_path')),
            sprintf('%s/big_arrow.png', config('nitro.image_path')),
        ],
    ],
    'ui-config' => [
        'image.library.notifications.url' => sprintf('%s/%s.png', config('nitro.notification_path'), '%image%'),
        'achievements.images.url' => sprintf('%s/%s.png', config('nitro.achievements_path'), '%image%'),
        'camera.url' => config('nitro.camera_url'),
        'thumbnails.url' => sprintf('%s/%s.png', config('nitro.thumbnail_path'), '%thumbnail%'),
        'url.prefix' => config('app.url'),
        'habbopages.url' => sprintf('%s/', config('app.url')),
        'group.homepage.url' => sprintf('%s/groups/%s/id', config('app.url'), '%groupid%'),
        'guide.help.alpha.groupid' => 0,
        'chat.viewer.height.percentage' => 0.4,
        'widget.dimmer.colorwheel' => false,
        'avatar.wardrobe.max.slots' => 10,
        'user.badges.max.slots' => 5,
        'user.tags.enabled' => false,
        'camera.publish.disabled' => false,
        'hc.disabled' => false,
        'badge.descriptions.enabled' => true,
        'motto.max.length' => 38,
        'bot.name.max.length' => 15,
        'pet.package.name.max.length' => 15,
        'wired.action.bot.talk.to.avatar.max.length' => 64,
        'wired.action.bot.talk.max.length' => 64,
        'wired.action.chat.max.length' => 100,
        'wired.action.kick.from.room.max.length' => 100,
        'wired.action.mute.user.max.length' => 100,
        'game.center.enabled' => false,
        'guides.enabled' => true,
        'toolbar.hide.quests' => true,
        'navigator.room.models' => [
            0 => ['clubLevel' => 0, 'tileSize' => 104, 'name' => 'a'],
            1 => ['clubLevel' => 0, 'tileSize' => 94, 'name' => 'b'],
            2 => ['clubLevel' => 0, 'tileSize' => 36, 'name' => 'c'],
            3 => ['clubLevel' => 0, 'tileSize' => 84, 'name' => 'd'],
            4 => ['clubLevel' => 0, 'tileSize' => 80, 'name' => 'e'],
            5 => ['clubLevel' => 0, 'tileSize' => 80, 'name' => 'f'],
            6 => ['clubLevel' => 0, 'tileSize' => 416, 'name' => 'i'],
            7 => ['clubLevel' => 0, 'tileSize' => 320, 'name' => 'j'],
            8 => ['clubLevel' => 0, 'tileSize' => 448, 'name' => 'k'],
            9 => ['clubLevel' => 0, 'tileSize' => 352, 'name' => 'l'],
            10 => ['clubLevel' => 0, 'tileSize' => 384, 'name' => 'm'],
            11 => ['clubLevel' => 0, 'tileSize' => 372, 'name' => 'n'],
            12 => ['clubLevel' => 1, 'tileSize' => 80, 'name' => 'g'],
            13 => ['clubLevel' => 1, 'tileSize' => 74, 'name' => 'h'],
            14 => ['clubLevel' => 1, 'tileSize' => 416, 'name' => 'o'],
            15 => ['clubLevel' => 1, 'tileSize' => 352, 'name' => 'p'],
            16 => ['clubLevel' => 1, 'tileSize' => 304, 'name' => 'q'],
            17 => ['clubLevel' => 1, 'tileSize' => 336, 'name' => 'r'],
            18 => ['clubLevel' => 1, 'tileSize' => 748, 'name' => 'u'],
            19 => ['clubLevel' => 1, 'tileSize' => 438, 'name' => 'v'],
            20 => ['clubLevel' => 2, 'tileSize' => 540, 'name' => 't'],
            21 => ['clubLevel' => 2, 'tileSize' => 512, 'name' => 'w'],
            22 => ['clubLevel' => 2, 'tileSize' => 396, 'name' => 'x'],
            23 => ['clubLevel' => 2, 'tileSize' => 440, 'name' => 'y'],
            24 => ['clubLevel' => 2, 'tileSize' => 456, 'name' => 'z'],
            25 => ['clubLevel' => 2, 'tileSize' => 208, 'name' => '0'],
            26 => ['clubLevel' => 2, 'tileSize' => 1009, 'name' => '1'],
            27 => ['clubLevel' => 2, 'tileSize' => 1044, 'name' => '2'],
            28 => ['clubLevel' => 2, 'tileSize' => 183, 'name' => '3'],
            29 => ['clubLevel' => 2, 'tileSize' => 254, 'name' => '4'],
            30 => ['clubLevel' => 2, 'tileSize' => 1024, 'name' => '5'],
            31 => ['clubLevel' => 2, 'tileSize' => 801, 'name' => '6'],
            32 => ['clubLevel' => 2, 'tileSize' => 354, 'name' => '7'],
            33 => ['clubLevel' => 2, 'tileSize' => 888, 'name' => '8'],
            34 => ['clubLevel' => 2, 'tileSize' => 926, 'name' => '9'],
        ],
        'hotelview' => [
            'show.avatar' => true,
            'widgets' => [
                'slot.1.widget' => '',
                'slot.1.conf' => [],
                'slot.2.widget' => '',
                'slot.2.conf' => [],
                'slot.3.widget' => '',
                'slot.3.conf' => [],
                'slot.4.widget' => '',
                'slot.4.conf' => [],
                'slot.5.widget' => '',
                'slot.5.conf' => [],
                'slot.6.widget' => '',
                'slot.6.conf' => [],
                'slot.7.widget' => '',
                'slot.7.conf' => [],
            ],
            'images' => [
                'background' => sprintf('%s/reception/stretch_blue.png', config('nitro.image_path')),
                'background.colour' => '#6eadc8',
                'sun' => sprintf('%s/reception/sun.png', config('nitro.image_path')),
                'drape' => sprintf('%s/reception/drape.png', config('nitro.image_path')),
                'left' => sprintf('%s/reception/ts.png', config('nitro.image_path')),
                'right' => sprintf('%s/reception/US_right.png', config('nitro.image_path')),
                'right.repeat' => sprintf('%s/reception/US_top_right.png', config('nitro.image_path')),
            ],
        ],
        'achievements.unseen.ignored' => [
            'ACH_AllTimeHotelPresence',
        ],
        'avatareditor.show.clubitems.dimmed' => true,
        'avatareditor.show.clubitems.first' => true,
        'chat.history.max.items' => 100,
        'system.currency.types' => [-1, 0, 5],
        'catalog.links' => [
            'hc.buy_hc' => 'habbo_club',
            'hc.hc_gifts' => 'club_gifts',
            'pets.buy_food' => 'pet_food',
            'pets.buy_saddle' => 'saddles',
        ],
        'hc.center' => [
            'benefits.info' => true,
            'payday.info' => true,
            'gift.info' => true,
            'benefits.habbopage' => 'habboclub',
            'payday.habbopage' => 'hcpayday',
        ],
        'respect.options' => [
            'enabled' => false,
            'sound' => 'sound_respect_received',
        ],
        'currency.display.number.short' => false,
        'currency.asset.icon.url' => sprintf('%s/%s.png', config('nitro.currency_icon_path'), '%type%'),
        'catalog.asset.url' => config('nitro.catalogue_path'),
        'catalog.asset.image.url' => sprintf('%s/%s.gif', config('nitro.catalogue_path'), '%name%'),
        'catalog.asset.icon.url' => sprintf('%s/icon_%s.png', config('nitro.catalogue_path'), '%name%'),
        'catalog.tab.icons' => false,
        'catalog.headers' => false,
        'chat.input.maxlength' => 100,
        'chat.styles.disabled' => [],
        'chat.styles' => [
            ['styleId' => 0, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 1, 'minRank' => 5, 'isSystemStyle' => true, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 2, 'minRank' => 5, 'isSystemStyle' => true, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 3, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 4, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 5, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 6, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 7, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 8, 'minRank' => 5, 'isSystemStyle' => true, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 9, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 10, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 11, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 12, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 13, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 14, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 15, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 16, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 17, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 18, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 19, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 20, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 21, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 22, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 23, 'minRank' => 5, 'isSystemStyle' => false, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 24, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 25, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 26, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 27, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 28, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 29, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 30, 'minRank' => 5, 'isSystemStyle' => true, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 31, 'minRank' => 5, 'isSystemStyle' => true, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 32, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 33, 'minRank' => 5, 'isSystemStyle' => true, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 34, 'minRank' => 5, 'isSystemStyle' => true, 'isHcOnly' => false, 'isAmbassadorOnly' => false],
            ['styleId' => 35, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 36, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
            ['styleId' => 37, 'minRank' => 5, 'isSystemStyle' => false, 'isHcOnly' => false, 'isAmbassadorOnly' => true],
            ['styleId' => 38, 'minRank' => 0, 'isSystemStyle' => false, 'isHcOnly' => true, 'isAmbassadorOnly' => false],
        ],
        'camera.available.effects' => [
            [
                'name' => 'dark_sepia',
                'colorMatrix' => [0.4, 0.4, 0.1, 0, 110, 0.3, 0.4, 0.1, 0, 30, 0.3, 0.2, 0.1, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'increase_saturation',
                'colorMatrix' => [2, -0.5, -0.5, 0, 0, -0.5, 2, -0.5, 0, 0, -0.5, -0.5, 2, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'increase_contrast',
                'colorMatrix' => [1.5, 0, 0, 0, -50, 0, 1.5, 0, 0, -50, 0, 0, 1.5, 0, -50, 0, 0, 0, 1.5, 0],
                'minLevel' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'shadow_multiply_02',
                'colorMatrix' => [],
                'minLevel' => 0,
                'blendMode' => 2,
                'enabled' => true,
            ],
            [
                'name' => 'color_1',
                'colorMatrix' => [0.393, 0.769, 0.189, 0, 0, 0.349, 0.686, 0.168, 0, 0, 0.272, 0.534, 0.131, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 1,
                'enabled' => true,
            ],
            [
                'name' => 'hue_bright_sat',
                'colorMatrix' => [1, 0.6, 0.2, 0, -50, 0.2, 1, 0.6, 0, -50, 0.6, 0.2, 1, 0, -50, 0, 0, 0, 1, 0],
                'minLevel' => 1,
                'enabled' => true,
            ],
            [
                'name' => 'hearts_hardlight_02',
                'colorMatrix' => [],
                'minLevel' => 1,
                'blendMode' => 9,
                'enabled' => true,
            ],
            [
                'name' => 'texture_overlay',
                'colorMatrix' => [],
                'minLevel' => 1,
                'blendMode' => 4,
                'enabled' => true,
            ],
            [
                'name' => 'pinky_nrm',
                'colorMatrix' => [],
                'minLevel' => 1,
                'blendMode' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'color_2',
                'colorMatrix' => [0.333, 0.333, 0.333, 0, 0, 0.333, 0.333, 0.333, 0, 0, 0.333, 0.333, 0.333, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 2,
                'enabled' => true,
            ],
            [
                'name' => 'night_vision',
                'colorMatrix' => [0, 0, 0, 0, 0, 0, 1.1, 0, 0, -50, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 2,
                'enabled' => true,
            ],
            [
                'name' => 'stars_hardlight_02',
                'colorMatrix' => [],
                'minLevel' => 2,
                'blendMode' => 9,
                'enabled' => true,
            ],
            [
                'name' => 'coffee_mpl',
                'colorMatrix' => [],
                'minLevel' => 2,
                'blendMode' => 2,
                'enabled' => true,
            ],
            [
                'name' => 'security_hardlight',
                'colorMatrix' => [],
                'minLevel' => 3,
                'blendMode' => 9,
                'enabled' => true,
            ],
            [
                'name' => 'bluemood_mpl',
                'colorMatrix' => [],
                'minLevel' => 3,
                'blendMode' => 2,
                'enabled' => true,
            ],
            [
                'name' => 'rusty_mpl',
                'colorMatrix' => [],
                'minLevel' => 3,
                'blendMode' => 2,
                'enabled' => true,
            ],
            [
                'name' => 'decr_conrast',
                'colorMatrix' => [0.5, 0, 0, 0, 50, 0, 0.5, 0, 0, 50, 0, 0, 0.5, 0, 50, 0, 0, 0, 1, 0],
                'minLevel' => 4,
                'enabled' => true,
            ],
            [
                'name' => 'green_2',
                'colorMatrix' => [0.5, 0.5, 0.5, 0, 0, 0.5, 0.5, 0.5, 0, 90, 0.5, 0.5, 0.5, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 4,
                'enabled' => true,
            ],
            [
                'name' => 'alien_hrd',
                'colorMatrix' => [],
                'minLevel' => 4,
                'blendMode' => 9,
                'enabled' => true,
            ],
            [
                'name' => 'color_3',
                'colorMatrix' => [0.609, 0.609, 0.082, 0, 0, 0.309, 0.609, 0.082, 0, 0, 0.309, 0.609, 0.082, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 5,
                'enabled' => true,
            ],
            [
                'name' => 'color_4',
                'colorMatrix' => [0.8, -0.8, 1, 0, 70, 0.8, -0.8, 1, 0, 70, 0.8, -0.8, 1, 0, 70, 0, 0, 0, 1, 0],
                'minLevel' => 5,
                'enabled' => true,
            ],
            [
                'name' => 'toxic_hrd',
                'colorMatrix' => [],
                'minLevel' => 5,
                'blendMode' => 9,
                'enabled' => true,
            ],
            [
                'name' => 'hypersaturated',
                'colorMatrix' => [2, -1, 0, 0, 0, -1, 2, 0, 0, 0, 0, -1, 2, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 6,
                'enabled' => true,
            ],
            [
                'name' => 'Yellow',
                'colorMatrix' => [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 6,
                'enabled' => true,
            ],
            [
                'name' => 'misty_hrd',
                'colorMatrix' => [],
                'minLevel' => 6,
                'blendMode' => 9,
                'enabled' => true,
            ],
            [
                'name' => 'x_ray',
                'colorMatrix' => [0, 1.2, 0, 0, -100, 0, 2, 0, 0, -120, 0, 2, 0, 0, -120, 0, 0, 0, 1, 0],
                'minLevel' => 7,
                'enabled' => true,
            ],
            [
                'name' => 'decrease_saturation',
                'colorMatrix' => [0.7, 0.2, 0.2, 0, 0, 0.2, 0.7, 0.2, 0, 0, 0.2, 0.2, 0.7, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 7,
                'enabled' => true,
            ],
            [
                'name' => 'drops_mpl',
                'colorMatrix' => [],
                'minLevel' => 8,
                'blendMode' => 2,
                'enabled' => true,
            ],
            [
                'name' => 'shiny_hrd',
                'colorMatrix' => [],
                'minLevel' => 9,
                'blendMode' => 9,
                'enabled' => true,
            ],
            [
                'name' => 'glitter_hrd',
                'colorMatrix' => [],
                'minLevel' => 10,
                'blendMode' => 9,
                'enabled' => true,
            ],
            [
                'name' => 'frame_gold',
                'colorMatrix' => [],
                'minLevel' => 10,
                'blendMode' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'frame_gray_4',
                'colorMatrix' => [],
                'minLevel' => 10,
                'blendMode' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'frame_black_2',
                'colorMatrix' => [],
                'minLevel' => 10,
                'blendMode' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'frame_wood_2',
                'colorMatrix' => [],
                'minLevel' => 10,
                'blendMode' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'finger_nrm',
                'colorMatrix' => [],
                'minLevel' => 10,
                'blendMode' => 0,
                'enabled' => true,
            ],
            [
                'name' => 'color_5',
                'colorMatrix' => [3.309, 0.609, 1.082, 0.2, 0, 0.309, 0.609, 0.082, 0, 0, 1.309, 0.609, 0.082, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 10,
                'enabled' => true,
            ],
            [
                'name' => 'black_white_negative',
                'colorMatrix' => [-0.5, -0.5, -0.5, 0, 0, -0.5, -0.5, -0.5, 0, 0, -0.5, -0.5, -0.5, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 10,
                'enabled' => true,
            ],
            [
                'name' => 'blue',
                'colorMatrix' => [0.5, 0.5, 0.5, 0, -255, 0.5, 0.5, 0.5, 0, -170, 0.5, 0.5, 0.5, 0, 0, 0, 0, 0, 1, 0],
                'minLevel' => 10,
                'enabled' => true,
            ],
            [
                'name' => 'red',
                'colorMatrix' => [0.5, 0.5, 0.5, 0, 0, 0.5, 0.5, 0.5, 0, -170, 0.5, 0.5, 0.5, 0, -170, 0, 0, 0, 1, 0],
                'minLevel' => 10,
                'enabled' => true,
            ],
            [
                'name' => 'green',
                'colorMatrix' => [0.5, 0.5, 0.5, 0, -170, 0.5, 0.5, 0.5, 0, 0, 0.5, 0.5, 0.5, 0, -170, 0, 0, 0, 1, 0],
                'minLevel' => 10,
                'enabled' => true,
            ],
        ],
        'notification' => [
            'notification.admin.transient' => [
                'display' => 'POP_UP',
                'image' => sprintf('%s/album1358/frank_wave_001.gif', config('nitro.c_images_path')),
            ],
            'notification.builders_club.membership_expired' => [
                'display' => 'POP_UP',
            ],
            'notification.builders_club.membership_expires' => [
                'display' => 'POP_UP',
                'image' => sprintf('%s/builders_club_room_locked_small.png', config('nitro.notification_path')),
            ],
            'notification.builders_club.membership_extended' => [
                'delivery' => 'PERSISTENT',
                'display' => 'POP_UP',
            ],
            'notification.builders_club.membership_made' => [
                'delivery' => 'PERSISTENT',
                'display' => 'POP_UP',
                'image' => sprintf('%s/builders_club_membership_extended.png', config('nitro.notification_path')),
            ],
            'notification.builders_club.membership_renewed' => [
                'delivery' => 'PERSISTENT',
                'display' => 'POP_UP',
                'image' => sprintf('%s/builders_club_membership_extended.png', config('nitro.notification_path')),
            ],
            'notification.builders_club.room_locked' => [
                'display' => 'BUBBLE',
                'image' => sprintf('%s/builders_club_room_locked_small.png', config('nitro.notification_path')),
            ],
            'notification.builders_club.room_unlocked' => [
                'display' => 'BUBBLE',
            ],
            'notification.builders_club.visit_denied_for_owner' => [
                'display' => 'BUBBLE',
                'image' => sprintf('%s/builders_club_room_locked_small.png', config('nitro.notification_path')),
            ],
            'notification.builders_club.visit_denied_for_visitor' => [
                'display' => 'POP_UP',
                'image' => sprintf('%s/builders_club_room_locked.png', config('nitro.notification_path')),
            ],
            'notification.campaign.credit.donation' => [
                'display' => 'BUBBLE',
            ],
            'notification.campaign.product.donation' => [
                'display' => 'BUBBLE',
            ],
            'notification.casino.too_many_dice.placement' => [
                'display' => 'POP_UP',
            ],
            'notification.casino.too_many_dice' => [
                'display' => 'POP_UP',
            ],
            'notification.cfh.created' => [
                'display' => 'POP_UP',
                'title' => '',
            ],
            'notification.feed.enabled' => false,
            'notification.floorplan_editor.error' => [
                'display' => 'POP_UP',
            ],
            'notification.forums.delivered' => [
                'delivery' => 'PERSISTENT',
                'display' => 'POP_UP',
            ],
            'notification.forums.forum_settings_updated' => [
                'display' => 'BUBBLE',
            ],
            'notification.forums.message.hidden' => [
                'display' => 'BUBBLE',
            ],
            'notification.forums.message.restored' => [
                'display' => 'BUBBLE',
            ],
            'notification.forums.thread.hidden' => [
                'display' => 'BUBBLE',
            ],
            'notification.forums.thread.locked' => [
                'display' => 'BUBBLE',
            ],
            'notification.forums.thread.pinned' => [
                'display' => 'BUBBLE',
            ],
            'notification.forums.thread.restored' => [
                'display' => 'BUBBLE',
            ],
            'notification.forums.thread.unlocked' => [
                'display' => 'BUBBLE',
            ],
            'notification.forums.thread.unpinned' => [
                'display' => 'BUBBLE',
            ],
            'notification.furni_placement_error' => [
                'display' => 'BUBBLE',
            ],
            'notification.gifting.valentine' => [
                'delivery' => 'PERSISTENT',
                'display' => 'BUBBLE',
                'image' => sprintf('%s/polaroid_photo.png', config('nitro.notification_path')),
            ],
            'notification.items.enabled' => true,
            'notification.mute.forbidden.time' => [
                'display' => 'BUBBLE',
            ],
            'notification.npc.gift.received' => [
                'display' => 'BUBBLE',
                'image' => sprintf('%s/album1584/X1517.gif', config('nitro.c_images_path')),
            ],
        ],
    ],
];
